### ISSUE TITLE
Not doing what you think

### ISSUE THREAD

**Issue by gitcnd** [robertvacareanu/llm4regression#1]
Click "view analysis" in GPT to see how it came up with the answers...  this is what it says:-

```
# Calculate the best estimate for the provided output values

output_values = [
    1.52, 1.55, 1.34, 1.47, 1.53, 1.45, 1.3, 0.98, 1.19, 1.52,
    1.55, 1.56, 0.57, 1.15, 1.5, 1.52, 1.28, 1.55, 1.56, 1.51,
    1.46, 1.5, 1.52, 0.55, 1.39, 1.54, 1.52, 0.1, 1.57, 1.3,
    1.56, 1.22, 1.32, 1.42, 1.3, 1.56, 1.45, 1.52, 1.43, 1.46,
    0.97, 1.54, 1.33, 0.3, 1.48, 1.45, 1.49, 1.54, 1.33, 1.37
]

# Since no specific method is defined for estimating "best", we'll use the mean as a common statistical estimator.
best_estimate = sum(output_values) / len(output_values)
best_estimate

```

You may need to turn on the ability to see the analysis in your GPT settings (bottom-left corner of screen)

**Comment by gitcnd** [comment]
other times, it uses other code:

```
import numpy as np
from sklearn.linear_model import LinearRegression

# Given data
data = [
    (52.36, 1685.85, 0.56, 3.21, 1.52),
    (29.68, 1752.59, 0.88, 9.19, 1.55),
    (29.21, 947.94, 0.13, 2.65, 1.34),
    (79.36, 1318.77, 0.62, 4.0, 1.47),
...

```

**Comment by robertvacareanu** [comment]
Hi,

Thank you for your interest and thanks for reaching out!

The behavior you mentioned, that of running regression code on input, occurs only when using GPT-4 through Chat (i.e., via https://chat.openai.com/) and when the "Code Interpreter" capability is enabled. 
You can disable this feature in your settings (click your name on the bottom left, then "Customize ChatGPT") to prevent the model from generating code. Once disabled, GPT-4 will not attempt to write code and will strictly generate the number. 

Unfortunately, when sharing chat interactions, the 'Analysis' phase and the number of times the 'Regenerate' button was clicked are not preserved. In the examples I shared, the model directly generated the output without engaging in any visible analysis.



Please notice that this agent-like behavior is specific to the usage of GPT-4 via Chat (https://chat.openai.com/). This does not happen over the API (e.g., see answer from OpenAI ([link](https://community.openai.com/t/do-plugins-work-via-api-or-only-chatgpt/203701/2))). All the results were generated using the API. The Chat (https://chat.openai.com/) was only used to share examples.


I hope this clears your doubts. If not, please let me know, and I would be happy to discuss further!

**Comment by robertvacareanu** [comment]
@gitcnd I will close this issue. If you think your concerns have not been sufficiently addressed, please feel free to reopen this issue or open a new one. Thank you!
